#!/usr/bin/env python3
"""
Parse historical-data.tsv from Google Sheets export and produce
SQL that inserts the data into the user's first household.
"""

import csv
import re
import sys
from pathlib import Path

MONTHS = {
    'jan': 1, 'januari': 1, 'january': 1,
    'feb': 2, 'februari': 2, 'february': 2,
    'mar': 3, 'maret': 3, 'march': 3,
    'apr': 4, 'april': 4,
    'mei': 5, 'may': 5,
    'jun': 6, 'juni': 6, 'june': 6,
    'jul': 7, 'juli': 7, 'july': 7,
    'aug': 8, 'agu': 8, 'agustus': 8, 'august': 8,
    'sep': 9, 'september': 9,
    'oct': 10, 'okt': 10, 'oktober': 10, 'october': 10,
    'nov': 11, 'november': 11,
    'dec': 12, 'des': 12, 'desember': 12, 'december': 12,
}


def parse_date(s: str, default_year: int = 2026):
    """Parse various date formats. Returns ISO date string or None."""
    s = s.strip().lower()
    if not s:
        return None
    # Normalize separators
    s = re.sub(r'[-/,]', ' ', s)
    s = re.sub(r'\s+', ' ', s).strip()
    tokens = s.split()
    day = month = None
    year = default_year
    for t in tokens:
        if t.isdigit():
            n = int(t)
            if n > 1900:
                year = n
            elif 1 <= n <= 31 and day is None:
                day = n
            elif 1 <= n <= 12 and month is None:
                month = n
        elif t in MONTHS:
            month = MONTHS[t]
        else:
            # token might have month name embedded
            for name, num in MONTHS.items():
                if t.startswith(name):
                    month = num
                    break
    if day and month:
        return f"{year:04d}-{month:02d}-{day:02d}"
    return None


def parse_amount(s: str):
    """Parse 'RP.    19,950.00' -> 19950. Returns int or None."""
    if not s:
        return None
    s = s.strip()
    if s in ('-', ''):
        return None
    # Remove "Rp." prefix (case-insensitive, optional dot)
    s = re.sub(r'^rp\.?\s*', '', s, flags=re.IGNORECASE).strip()
    # Remove trailing .00 / ,00
    s = re.sub(r'[.,]00$', '', s)
    # Remove thousand separators (both . and ,)
    s = s.replace(',', '').replace('.', '').replace(' ', '')
    if not s:
        return None
    try:
        n = int(s)
        return n if n > 0 else None
    except ValueError:
        return None


def sql_escape(s: str) -> str:
    return s.replace("'", "''")


def main():
    src = Path(__file__).parent / 'historical-data.tsv'
    out = Path(__file__).parent.parent / 'supabase' / 'migrations' / '0002_import_historical.sql'

    rows = []
    current_date = None
    skipped_no_date = skipped_no_amount = skipped_no_cat = skipped_header = 0

    with src.open() as f:
        for line in f:
            line = line.rstrip('\n')
            if not line.strip():
                continue
            parts = line.split('\t')
            # Pad to 4 columns
            while len(parts) < 4:
                parts.append('')
            date_str, desc, cat, amt_str = parts[0], parts[1], parts[2], parts[3]

            if date_str.strip():
                parsed = parse_date(date_str)
                if parsed:
                    current_date = parsed
                else:
                    # Likely a header label like "Gajian"
                    skipped_header += 1
                    continue

            if not current_date:
                skipped_no_date += 1
                continue

            desc = desc.strip()
            cat = cat.strip()
            if not desc or desc == '-':
                continue
            if not cat or cat == '-':
                skipped_no_cat += 1
                continue
            amount = parse_amount(amt_str)
            if amount is None:
                skipped_no_amount += 1
                continue

            rows.append((current_date, desc, cat, amount))

    # Discover unique categories
    cats = sorted(set(r[2] for r in rows))
    print(f"Total expense rows: {len(rows)}", file=sys.stderr)
    print(f"Unique categories used: {len(cats)}", file=sys.stderr)
    for c in cats:
        print(f"  - {c}", file=sys.stderr)
    print(f"Skipped — no amount: {skipped_no_amount}, no category: {skipped_no_cat}, header: {skipped_header}", file=sys.stderr)

    # Generate SQL
    sql_lines = [
        "-- =====================================================================",
        "-- Import historical expense data from Google Sheets (Jan 21 - May 26, 2026)",
        "-- Generated by scripts/parse_historical.py",
        "--",
        "-- HOW TO RUN:",
        "--   1. Log in to your app at least once (so your household is provisioned).",
        "--   2. Open Supabase SQL Editor → New query → paste this file → Run.",
        "--   3. The script auto-targets the household for user with email matching",
        "--      the variable below — change it if needed.",
        "-- =====================================================================",
        "",
        "do $$",
        "declare",
        "  v_user_email text := 'YOUR_EMAIL_HERE@gmail.com';  -- TODO: change this!",
        "  v_user_id uuid;",
        "  v_household_id uuid;",
        "begin",
        "  -- Find user",
        "  select id into v_user_id from auth.users where email = v_user_email;",
        "  if v_user_id is null then",
        "    raise exception 'User % not found. Log in to the app first.', v_user_email;",
        "  end if;",
        "",
        "  -- Find user's household",
        "  select household_id into v_household_id",
        "  from household_members where user_id = v_user_id limit 1;",
        "  if v_household_id is null then",
        "    raise exception 'No household for user %', v_user_email;",
        "  end if;",
        "",
        "  -- Ensure all categories used in the data exist",
        "  insert into categories (household_id, name, color, sort_order)",
        "  select v_household_id, x.name, x.color, x.sort_order from (values",
    ]

    # Cat seed values (color + sort), default for unknown is amber
    cat_defaults = {
        'Tagihan': ('#ef4444', 1),
        'Kebutuhan Anak': ('#f97316', 2),
        'Kebutuhan Rumah Tangga': ('#eab308', 3),
        'Makan': ('#22c55e', 4),
        'Transportasi': ('#06b6d4', 5),
        'Kebutuhan Tambahan': ('#3b82f6', 6),
        'Self Reward Umma': ('#a855f7', 7),
        'Self Reward Abbi': ('#ec4899', 8),
        'Kebutuhan Kultural': ('#14b8a6', 9),
        'Nabung': ('#64748b', 10),
        'Kebutuhan Keinginan': ('#f59e0b', 11),
    }
    cat_value_lines = []
    sort_counter = 100
    for c in cats:
        color, sort = cat_defaults.get(c, ('#94a3b8', sort_counter))
        cat_value_lines.append(f"    ('{sql_escape(c)}', '{color}', {sort})")
        sort_counter += 1
    sql_lines.append(',\n'.join(cat_value_lines))
    sql_lines += [
        "  ) as x(name, color, sort_order)",
        "  on conflict (household_id, name) do nothing;",
        "",
        "  -- Insert expenses",
        "  with data(spent_at, description, category_name, amount) as (values",
    ]

    expense_value_lines = []
    for d, desc, cat, amount in rows:
        expense_value_lines.append(
            f"    ('{d}'::date, '{sql_escape(desc)}', '{sql_escape(cat)}', {amount}::numeric)"
        )
    sql_lines.append(',\n'.join(expense_value_lines))
    sql_lines += [
        "  )",
        "  insert into expenses (household_id, category_id, spent_at, description, amount, created_by)",
        "  select v_household_id, c.id, d.spent_at, d.description, d.amount, v_user_id",
        "  from data d",
        "  join categories c on c.household_id = v_household_id and c.name = d.category_name;",
        "",
        f"  raise notice 'Imported % expense rows for household %', {len(rows)}, v_household_id;",
        "",
        "  -- Backfill monthly budgets for historical months (Jan-May 2026)",
        "  -- so dashboard shows proper progress when navigating back",
        "  insert into budgets (household_id, category_id, month, amount)",
        "  select v_household_id, c.id, m.month,",
        "    case c.name",
        "      when 'Tagihan'                then 1000000",
        "      when 'Kebutuhan Anak'         then 5000000",
        "      when 'Kebutuhan Rumah Tangga' then 1000000",
        "      when 'Makan'                  then 3000000",
        "      when 'Transportasi'           then 2000000",
        "      when 'Kebutuhan Tambahan'     then 500000",
        "      when 'Self Reward Umma'       then 1000000",
        "      when 'Self Reward Abbi'       then 500000",
        "      when 'Kebutuhan Kultural'     then 4000000",
        "      when 'Kebutuhan Keinginan'    then 500000",
        "      else 0",
        "    end",
        "  from categories c",
        "  cross join (values",
        "    ('2026-01-01'::date), ('2026-02-01'::date), ('2026-03-01'::date),",
        "    ('2026-04-01'::date), ('2026-05-01'::date)",
        "  ) as m(month)",
        "  where c.household_id = v_household_id",
        "  on conflict (category_id, month) do nothing;",
        "end $$;",
        "",
    ]

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text('\n'.join(sql_lines))
    print(f"\nGenerated: {out}", file=sys.stderr)


if __name__ == '__main__':
    main()
